# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: Example
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Test
      env:
        LIVECHAT_DOMAIN: ${{ secrets.LIVECHAT_DOMAIN }}
        LIVECHAT_VERSION: ${{ secrets.LIVECHAT_VERSION }}
        LIVECHAT_ORGANIZATION_ID: ${{ secrets.LIVECHAT_ORGANIZATION_ID }}
        LIVECHAT_DEPLOYMENT_ID: ${{ secrets.LIVECHAT_DEPLOYMENT_ID }}
        LIVECHAT_BUTTON_ID: ${{ secrets.LIVECHAT_BUTTON_ID }}
        LIVECHAT_AGENT_ID: ${{ secrets.LIVECHAT_AGENT_ID }}
        LIVECHAT_CONTAC_ID: ${{ secrets.LIVECHAT_CONTAC_ID }}
      run: go test -v ./...
